### ISSUE TITLE
Cura Support settings

### ISSUE THREAD

**Issue by c0pp3r** [Kyle-Cerniglia/EvE-3D-Printing#10]
I'm having some issues getting these to print. It seems like the printer (ender 3) is having issues getting the supports down. Is there something I'm doing wrong? Using Cura as my slicer.

**Comment by Kyle-Cerniglia** [comment]
I'm not too familiar with Cura, the only slicer that I've really used was Slic3r.
Were the supports just not sticking to the baseplate well?
