### ISSUE TITLE
Textures?

### ISSUE THREAD

**Issue by DragionTEI** [Kyle-Cerniglia/EvE-3D-Printing#2]
Hello,

could u add the textures? (if u can)

thx,
p.s does triexporter work on a steam installation?

**Comment by Kyle-Cerniglia** [comment]
I'm not sure how to use the textures, I dont believe triexporter renders them right to see what theyre doing, but yes, I believe that the steam installation should work, it would just be a matter of finding the game folder.

**Comment by DragionTEI** [comment]
Thx
