### ISSUE TITLE
SOE ship files are broken?

### ISSUE THREAD

**Issue by Gr33nShade** [Kyle-Cerniglia/EvE-3D-Printing#4]
Hi!
I noticed that the SOE ships are uploaded as .obj file. I wouldn't mind this, but when I try to load them, they all seem to be empty. The preview of the Astero is a list of coordinates, which should make the model, or at least be visible, but there is nothing to see.
Could you please change these files to be .stl like everything else?
Thank you!

**Comment by Kyle-Cerniglia** [comment]
Welp, not sure how I missed that, lol. Fixed
