### ISSUE TITLE
Typhoon new model

### ISSUE THREAD

**Issue by lethalshadow** [Kyle-Cerniglia/EvE-3D-Printing#9]
Typhoon has a new model in the game. This collection is awesome btw, printed out a bunch from it. Simplify3D complains about the Abaddon model - says it has self intersecting surfaces.

**Comment by Kyle-Cerniglia** [comment]
Typhoon has been updated.
I also ran the Abaddon through repair again, but I'm not sure if that fixed the issue that you were having.
